from time import sleep
def start():
    name = "viewer"
    print("\t\ti i i")
    sleep(1)
    print("\t\ti i i")
    sleep(1)
    print("\t:--------------------------:")
    print("\t:    Happy        ++++     :")
    sleep(1)
    print("\t:     ++++      Birthday   :")
    sleep(1)
    print("\t:    {name}       ++++   | :")
    print("\t/_________________________\ ")
    sleep(1)
    print("\t:-:-:-:-:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)
    print("\t:-:-:-:-:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)    
    print("\t:-:-:-:-:-:-:-:-:-:-:-:-:-:-:")
    sleep(.25)
    print("\t=============================")
    sleep(.25)
    print("\t||  ||  ||  ||  ||  ||  ||  ||")
    sleep(.25) 
    print("\t||  ||  ||  ||  ||  ||  ||  ||")
    sleep(.25)  
    print("\t||  ||  ||  ||  ||  ||  ||  ||")
    sleep(.25)  
    print("\t||  ||  ||  ||  ||  ||  ||  ||")
    sleep(.5)
    print("Loading......")
    sleep(1)
    print("A message to you......")
    sleep(4)
    print("\t MAY GOD BLESS YOU!! :) ")

a = input("1.TYPE 'win' \n 2.PRESS 'ENTER' KEY \n (ELSE TYPE 'QUIT' TO QUIT) \n\n: ")

if (a == "win"):
    start()
else:
    print("BYE!!")